spring:
  application:
    name: emos-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysqlyyds123
    #以下为连接池的相关参数配置
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.79.132.241:3306/sys-oa?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  redis:
    database: 0
    host: 120.79.132.241
    password: redisyyds123
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb://admin:mongoyyds123@120.79.132.241:27017/emos?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256

server:
  port: 8888

minio:
  url: http://119.91.113.111:9000
  secretId: admin
  secretKey: admin123456