spring:
  application:
    name: emos-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysqlyyds123
    #type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    minIdle: 10
    maxActive: 20
    maxWait: 6000
    validationQuery: SELECT 1 FROM DUAL
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    url: jdbc:mysql://120.79.132.241:3306/sys-oa?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  redis:
    database: 0
    host: 120.79.132.241
    password: redisyyds123
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      host: 120.79.132.241
      port: 27017
      username: admin
      password: mongoyyds123
server:
  port: 8888
